import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');

const systemPrompt = readFileSync(resolve(rootDir, 'templates/system-prompt.md'), 'utf-8');
const reportTemplate = readFileSync(resolve(rootDir, 'templates/report-template.md'), 'utf-8');

const outputDir = resolve(rootDir, 'packages/action/src/generated');
mkdirSync(outputDir, { recursive: true });

const outputContent = [
  '// AUTO-GENERATED — do not edit manually.',
  '// Generated by scripts/embed-templates.ts from templates/*.md',
  '',
  'export const SYSTEM_PROMPT = ' + JSON.stringify(systemPrompt) + ';',
  '',
  'export const REPORT_TEMPLATE = ' + JSON.stringify(reportTemplate) + ';',
  '',
].join('\n');

writeFileSync(resolve(outputDir, 'templates.ts'), outputContent, 'utf-8');

console.log('Generated packages/action/src/generated/templates.ts');
